sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
before_install:
  - sudo apt-get install expect
  - sudo apt-get install libnotify-bin
install:
  - npm install
script:
  - npm run build
  - npm test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
